export enum Events {
  JOIN = 'join',
  USER_JOINED = 'user-joined',
  SEND_MESSAGE = 'send-message',
  RECEIVE_MESSAGE = 'receive-message',
  REQUEST_ALL_MESSAGES = 'request-all-messages',
  SEND_ALL_MESSAGES = 'send-all-messages',
  CREATE_CHAT = 'create-chat',
  RECEIVE_CHAT = 'receive-chat',
  REQUEST_ALL_CHATS = 'request-all-chats',
  SEND_ALL_CHATS = 'send-all-chats',
  LEAVE = 'leave',
  USER_LEFT = 'user-left',
  CHATS = 'chats',
  NEW_CHAT = 'new-chat',
  ERROR = 'error',
}
