services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    restart: always
    env_file:
      - .development.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  redis:
    driver: local
