version: '3.8'

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    env_file:
      - .development.env
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - redis-data:/data
